In [1]:
import numpy as np
import matplotlib.pyplot as plt
# here we are working on Tensorflow version 2.1.0 so we need to write tensorflow.keras.
#keras is in built function in Tensorflow.
import os
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dense, Input, Dropout,Flatten, Conv2D
from tensorflow.keras.layers import BatchNormalization, Activation, MaxPooling2D
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau
from tensorflow.keras.utils import plot_model
from IPython.display import SVG, Image

In [2]:
train_location = "C:\\Users\\DELL 5540\\Desktop\\SCAD-main\\SCAD-main\\dataset"
test_location = "C:\\Users\\DELL 5540\\Desktop\\SCAD-main\\SCAD-main\\dataset"
filepath = 'C:\\Users\\DELL 5540\\Desktop\\SCAD-main\\SCAD-main\\model\\Sickle_VGG16_model_M1.h5'

In [3]:
from tensorflow.keras.models import load_model
Detection=load_model(filepath)

In [4]:
img_size=224
batch_size=3
num_class=3

In [5]:
# Complete Dataset images can be loaded using ImageDataGenerator function

datagen_train=ImageDataGenerator(horizontal_flip=True)
train_generator=datagen_train.flow_from_directory(train_location,target_size=(img_size,img_size),batch_size=batch_size,class_mode='categorical',shuffle=True)

datagen_test=ImageDataGenerator(horizontal_flip=True)
validation_generator=datagen_test.flow_from_directory(test_location,target_size=(img_size,img_size),batch_size=batch_size,class_mode='categorical',shuffle=True)


Found 756 images belonging to 3 classes.


Found 756 images belonging to 3 classes.


In [6]:
classes=train_generator.class_indices
classes

{'Sickle-ISC': 0, 'normal rbc': 1, 'thaleesmia': 2}

In [7]:
category=[]
for i in classes:
          category.append(i)

category

['Sickle-ISC', 'normal rbc', 'thaleesmia']

In [8]:
from skimage import io
import os
from tensorflow.keras.preprocessing import image

image_directory=test_location
dataset = []
predict_result=[]
label =[]


my_folders = os.listdir(image_directory)
for i, folder_name in enumerate(my_folders):
    #print(str(i)+': ' +folder_name)

    loc=0
    for j in category:
      if(j==folder_name):
        lab=loc
      loc+=1
    lab

    my_images = os.listdir(image_directory+'/'+folder_name)
    for j,image_name in enumerate(my_images):
      #print(str(j)+': ' +image_name)

      file_name = image_directory+'/'+folder_name + '/' + image_name

      test_img=image.load_img(file_name,target_size=(img_size,img_size))
      test_img=image.img_to_array(test_img)
      test_img=np.expand_dims(test_img,axis=0)
      result=Detection.predict(test_img)

      label.append(lab)
      predict_result.append(result.argmax())

      print(f'{folder_name} : {str(lab)} , Predicted : {result.argmax()}  ')




1/1 [==============================] - 0s 351ms/step
normal rbc : 1 , Predicted : 1  
1/1 [==============================] - 0s 141ms/step
normal rbc : 1 , Predicted : 1  
1/1 [==============================] - 0s 137ms/step
normal rbc : 1 , Predicted : 1  
1/1 [==============================] - 0s 181ms/step
normal rbc : 1 , Predicted : 1  
1/1 [==============================] - 0s 185ms/step
normal rbc : 1 , Predicted : 1  
1/1 [==============================] - 0s 120ms/step
normal rbc : 1 , Predicted : 1  
1/1 [==============================] - 0s 120ms/step
normal rbc : 1 , Predicted : 1  
1/1 [==============================] - 0s 133ms/step
normal rbc : 1 , Predicted : 1  
1/1 [==============================] - 0s 124ms/step
normal rbc : 1 , Predicted : 1  
1/1 [==============================] - 0s 128ms/step
normal rbc : 1 , Predicted : 1  
1/1 [==============================] - 0s 125ms/step
normal rbc : 1 , Predicted : 2  
1/1 [==============================] - 0s 134ms/step
n

In [9]:
correct=0
Wrong=0


for i in range(len(label)):
  if(predict_result[i]==label[i]):
    correct+=1
  else:
    Wrong+=1

print(f'correct: {correct} , Wrong: {Wrong}')




correct: 747 , Wrong: 10


In [10]:
Acc= correct/(correct+Wrong)
Acc*100

98.67899603698811

In [11]:

y_test = label
y_pred = predict_result

In [12]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score
from sklearn.metrics import classification_report
from sklearn import metrics

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('Test set accuracy: ',metrics.accuracy_score(y_test, y_pred))

[[ 96   0   0]
 [  0 343   6]
 [  4   0 308]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98        96
           1       1.00      0.98      0.99       349
           2       0.98      0.99      0.98       312

    accuracy                           0.99       757
   macro avg       0.98      0.99      0.98       757
weighted avg       0.99      0.99      0.99       757

Test set accuracy:  0.9867899603698811


In [13]:
confusion = metrics.confusion_matrix(y_test, y_pred)
confusion.ravel()

array([ 96,   0,   0,   0, 343,   6,   4,   0, 308], dtype=int64)

In [14]:
accuracy = metrics.accuracy_score(y_test, y_pred)
accuracy

0.9867899603698811